version: '3.8'

services:

  php-apache-environment:
    container_name: php-apache
    build:
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./public:/var/www/html
    ports:
      - 8000:80
