version: '3.8'

services:

  php-apache-environment:
    container_name: php-apache
    build: ./
    volumes:
      - ./mycert.crt:/etc/ssl/certs/mycert.crt
      - ./mycert.key:/etc/ssl/private/mycert.key
      - ./public:/var/www/html
    ports:
      - 8000:80
      - 8443:443
